services:
  database:
    image: postgres:alpine
    volumes:
      - /var/lib/docker/postgres_host_volume:/var/lib/postgresql/data/db-files
    ports:
      - 5432:5432
    restart: always

    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: exampledb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/db-files/
    secrets:
      - my_db_pass

secrets:
  my_db_pass:
  external: true

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
